[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["{{ name }}.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
dir = 'lib'
use = ['*.zsh']

[plugins.ohmyzsh-plugins]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins'
use = [
    '{git,zoxide}/*.plugin.zsh',
]
