name: Run install script

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test-script-install:
    runs-on: ubuntu-latest
    container:
      image: debian:stable

    steps:
      - uses: actions/checkout@v2
      - name: Run install script
        run: ./install.sh
